// Socket events
export const SOCKET_USER_ENTER = '@@SOCKET/USER_ENTER';
export const SOCKET_UPDATE_USERS_LIST = '@@SOCKET/UPDATE_USERS_LIST';
export const SOCKET_POST_MESSAGE = '@@SOCKET/POST_MESSAGE';
export const SOCKET_UPDATE_MESSAGES = '@@SOCKET/UPDATE_MESSAGES';
export const SOCKET_UPDATE_TIMER = '@@SOCKET/UPDATE_TIMER';
export const SOCKET_POST_LAUGHT = '@@SOCKET/POST_LAUGHT';
